# https://1cloud.ru/blog/yaml_for_beginners
---
tg:
 "chat_id": "-1001559306561"
 "token": "5433315725:AAEIyq5r-Zn-XtQjaWgWeHtrQ8XDHiRQ0mk"

text_settings:
 "min_text_size": 550 # text length to run summarizator

key_words_countries:
 - "South America":
   - "Peru"
   - "Chile"
   - "Colombia"

 - "Central America":
   - "Mexico"
   - "Panama"

 - "Brazil":
   - "Brazil"
